### ISSUE TITLE
Modifier version

### ISSUE THREAD

**Issue by cah-briangantzler** [sinankeskin/ember-litepicker#64]
Would you be open to a modifier version being created that would allow this to be attached to any element.

Looking at the code, its basically a modifier already, would be an easy update

**Comment by cah-briangantzler** [comment]
Since you added enhancement, I would be happy to provide a PR for this

**Comment by sinankeskin** [comment]
Please feel free.

**Comment by sinankeskin** [comment]
PR merged.
