### ISSUE TITLE
Cant pass dates into component

### ISSUE THREAD

**Issue by cah-briangantzler** [sinankeskin/ember-litepicker#65]
The options that are dates (start, end, min, max) cant be passed in as Date objects even though Litepicker will accept them. This is because https://github.com/sinankeskin/ember-litepicker/blob/master/addon/components/litepicker.js#L272 makes a copy if the option is an object, you cant do that with dates. What was the reason for making the copy if its an object instead of just using the param that is passed in?

**Comment by sinankeskin** [comment]
args is a special kind of object. Looks plain old javascript object but actually is not. That's why I use Object.assign in my every addon for normalize.

Also this is really odd because I'm using Date and moment objects in my project without a issue like down below.

```handlebars
<Litepicker
  id={{el.id}}
  placeholder="Tarih Aralığı"
  class="form-control {{el.validation}}"
  readonly="readonly"
  autocomplete="off"
  @singleMode={{false}}
  @numberOfMonths={{2}}
  @numberOfColumns={{2}}
  @onSelect={{fn this.onSelect}}
  @startDate={{this.startDate}}
  @endDate={{this.endDate}}
  @minDate={{this.minDate}}
  @maxDate={{this.maxDate}}
/>
```

```javascript
@computed('args.model')
get startDate() {
  if (isPresent(this.args.model.get('startDate'))) {
    return this.args.model.get('startDate');
  }

  return null;
}

@computed
get minDate() {
  return moment().format('YYYY-MM-DD');
}
```

**Comment by cah-briangantzler** [comment]
You are NOT passing the Date or Moment object, you are passing a formatted string in the `minDate`, the above code does not tell me what startDate looks like, just that it in a property of model

In the Dummy app of this addon you have in applicaiton.hbs (passing strings)
```hbs
<Litepicker @singleMode={{false}} @startDate="23.12.2019" @endDate="28.12.2019" autocomplete="off" />
```

When the app initially shows, the date range shows in the input field.

change to this
```hbs
{{log "startDate" this.startDate}}
{{log "endDate" this.endDate}}
<Litepicker @singleMode={{false}} @startDate={{this.startDate}} @endDate={{this.endDate}} autocomplete="off" />
```

create and add this to the application controller
```js
  startDate = new Date(2019, 11, 23); // the month is 0-indexed
  endDate = new Date(2019, 11, 23); // the month is 0-indexed
```

Now you are passing dates, you will see the logs says the dates are correct, but they do NOT show in the input anymore. If thinks you passed no dates. Litepicker docs says it supports Date/Number/String.   This addon only supports Number/String because of the following.




For the this.args property, I do realize its a special object, but is this.args.buttonText (had I passed that as a param) a special object or just a hash? 

```js
Object.keys(this.args).forEach((option) => {
      const _option = get(this.args, option);

      if (typeof _option === 'object') {
        options[option] = Object.assign({}, _option);
      } else {
        options[option] = _option;
      }
    });
```

```hbs
<Litepicker @buttonText={{hash apply='Hit me'}} />
```

instead of doing 
```js
    options['buttonText'] = _option
```

it will see it as an object and do 
```js
    options['buttonText'] = Object.assign({}, _option);
```

Was that really needed? wasnt buttonText just a hash on this.args?

if also means that it will do the equiv of this
```js
    options['startDate'] = Object.assign({}, Date());
```

If you look at that you see the new option is just a hash, not a date, it lost its prototype. You can get away with object assign if its a hash, you cant if its a real object.

I understand not just passing this.args onto litepicker and creating a new hash to pass, just take out the === 'object' check in the forEach and always just assign _option.

That should fix the ability to pass Date (probably Moment) objects

**Comment by cah-briangantzler** [comment]
Fixed with https://github.com/sinankeskin/ember-litepicker/pull/74
