### ISSUE TITLE
Provide an API access to the Litepicker object

### ISSUE THREAD

**Issue by cah-briangantzler** [sinankeskin/ember-litepicker#66]
Provide an API access to the Litepicker object so that we are able to programmatically hide and display the picker for instance as well as access to any of the other methods

**Comment by cah-briangantzler** [comment]
Since you added enhancement I would be happy to provide a PR for this

**Comment by cah-briangantzler** [comment]
Do you have a preference? Should just the litepicker instance be returns, so they could call the methods exposed? https://wakirin.github.io/Litepicker/#anchor-Methods and new methods would just be available. Or would you prefer an api object returned that only exposed the methods we want (not exposing destroy for instance) but would mean we would have to expose each new method.

**Comment by sinankeskin** [comment]
I think best way is the yielding the instance. So that way every method can be reach easily via instance.
