### ISSUE TITLE
Allow for the date range to link to 2 different inputs

### ISSUE THREAD

**Issue by cah-briangantzler** [sinankeskin/ember-litepicker#75]
Lite picker has the ability to link to two different inputs for the start and end date of a range. Allow for this addon to take advantage of that.

**Comment by sinankeskin** [comment]
I'm thinking how to implement this. I will in a short time hopefully.

Thanks.

**Comment by sinankeskin** [comment]
Hi @cah-briangantzler 

With [element-ref-bucket](https://github.com/lifeart/ember-ref-bucket) you can easily link two inputs. You can pass reference to elementEnd parameter.

Here is the screenshot.

![linked](https://user-images.githubusercontent.com/2091777/106010127-26782380-60ca-11eb-976f-668ff4396d9d.png)

Closing. Thanks.
