### ISSUE TITLE
Allow for the module litepicker-module-ranges to be accessed through this addon

### ISSUE THREAD

**Issue by cah-briangantzler** [sinankeskin/ember-litepicker#76]
Litepicker has the ability to inject custom modules. litepicker-module-ranges is one that I would like to use. Using this addon, what is the correct way to add this modules capability?

**Comment by sinankeskin** [comment]
Hi @cah-briangantzler 

I lost my father about 10 days ago. My psychology is a total mess.
I don't wanna do anything about code. I don't even come near to my computer.

If you'd like to I can add you as a collaborator. You can change whatever you want.

**Comment by cah-briangantzler** [comment]
Sorry to hear that. Lost my father a year ago June, So I feel ya.

Most the big ones I wanted to do I have got done, the recent issues I have had to think about before I put a PR anyway.

You can do that if you wish, but will prob not do an actual release until you get back, Thanks for what you have done so far.

**Comment by sinankeskin** [comment]
Hey @cah-briangantzler 

I've just added this feature. You can import modules dynamically now with `modules: ['ranges', 'navkeyboard']` option in `ENV['ember-litepicker'] config`.

Thanks.
